<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-10-04 09:20

$extensionPath = t3lib_extMgm::extPath('phamlp');
$extensionClassesPath = t3lib_extMgm::extPath('phamlp') . 'Classes/';
return array(
	'tx_phamlp_pi1' => $extensionClassesPath . 'Pi1/class.tx_phamlp_pi1.php',
	'tx_phamlp_utils_phamlputil' => $extensionClassesPath . 'Utils/PhamlpUtil.php',
);
?>